### ISSUE TITLE
No host supplied error 5.0.3 Using Readme Example

### ISSUE THREAD

**Issue by dwchowscalesec** [PaloAltoNetworks/prismacloud-api-python#103]
## Describe the bug

Using the exact sample on the Readme results in a requests package exception: "requests.exceptions.InvalidURL: Invalid URL 'https:///login': No host supplied"

## Expected behavior
Returned details of the current user

## Current behavior
requests.exceptions.InvalidURL: Invalid URL 'https:///login': No host supplied

## Possible solution
Unknown

## Steps to reproduce
1. python -m venv .
2. source bin/activate 
3. pip3 install prismacloud-api
4. python3 foo.py

#code used
`import os
from prismacloud.api import pc_api

# Settings for Prisma Cloud Enterprise Edition

settings = {
    "url":      "https://api.prismacloud.io/",
    "identity": "access_key",
    "secret":   "secret_key"
}

pc_api.configure(settings)

print('Prisma Cloud API Current User:')
print()
print(pc_api.current_user())
print()
print('Prisma Cloud Compute API Intelligence:')
print()
print(pc_api.statuses_intelligence())
print()`

## Context
Basic utilization of the API
Also attempted changing url with or without trailing '/' and use of api2.prismacloud.io

## Your Environment
- Version used: 5.0.3
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3): Python 3.10.6
- Operating System and version (desktop or mobile): MacOS

**Comment by dwchowscalesec** [comment]
Closing as I was able to correctly use this changing the parameter to:
`settings = {
    "url":      "api2.prismacloud.io",
    "identity": "foo",
    "secret":   "bar"
}`

**Comment by tkishel** [comment]
Thanks Dennis. No, this is a bug, fixed in 5.0.4!
