### ISSUE TITLE
Usage of the sys.exit

### ISSUE THREAD

**Issue by mgappa** [PaloAltoNetworks/prismacloud-api-python#118]
### Is your feature request related to a problem?

I'm concerned about the usage of the `sys.exit` function, for all API calls.

### Describe the solution you'd like

I would like to replace all `sys.exit`, with a set of Exception (Python native or custom)

### Describe alternatives you've considered

I have considered using:
* The usage of `self.execute`, with the flag `force` but if there are some missing or misspellings, identity or secret or URL, during the login phase, then the `exit` is still present
* The overloading of the function `error_and_exit`, however it's some works for a little gain

### Additional context

In my enterprise context, we want to use the SDK, on AWS Lambda, and it's not a best practice to use a `sys.exit`.

**Comment by mgappa** [comment]
Hello,
I can submit a pull request if you want. I think the `SystemExit` can make the job

**Comment by tkishel** [comment]
I've got it!
