### ISSUE TITLE
Request to add wrapper of api/v1/registry/names

### ISSUE THREAD

**Issue by diogoraposo** [PaloAltoNetworks/prismacloud-api-python#125]
### Is your feature request related to a problem?
No

### Describe the solution you'd like
Add the following snippet to prismacloud/api/compute/_registry.py:
`def registry_list_names(self, body_params=None):
        result = self.execute_compute('GET', 'api/v1/registry/names', body_params=body_params)
        return result`

### Describe alternatives you've considered
Have to implement this locally, but I use it in lambdas which have an automated deployment. It would make it easier to deploy and reduce complexity of my deployment to have it in the package installed via requirements.txt

**Comment by tkishel** [comment]
Thanks! That endpoint is a GET, so should use query params rather than body params:

https://prisma.pan.dev/api/cloud/cwpp/registry#operation/get-registry-names

So I'll add this:

```
    def registry_list_image_names(self, query_params=None):
        result = self.execute_compute('GET', 'api/v1/registry/names?', query_params=query_params)
        return result
```

**Comment by tkishel** [comment]
Resolved via https://github.com/PaloAltoNetworks/prismacloud-api-python/pull/126
