### ISSUE TITLE
endpoint to Get resource timeline

### ISSUE THREAD

**Issue by rinaudjaws** [PaloAltoNetworks/prismacloud-api-python#145]
### Is your feature request related to a problem?

I want to retrieve the audit trail of changes for a resource to detect manual changes.

### Describe the solution you'd like

Extended class with with get_resource_timeline (https://pan.dev/prisma-cloud/api/cspm/get-timeline-for-resource/)

### Describe alternatives you've considered

Building myself or forking code

### Additional context

See problem above.

**Comment by tkishel** [comment]
Feel free to submit a PR, using this documentation to add the method:

https://github.com/PaloAltoNetworks/prismacloud-api-python/tree/main/prismacloud/api/cspm

Or just call the endpoint directly in your script via: 

```
result = pc_api.execute('POST', 'resource/timeline', body_params={...})
```

**Comment by rinaudjaws** [comment]
Thank you, implemented that work around.
