### ISSUE TITLE
AttributeError: 'PrismaCloudAPI' object has no attribute 'hosts_list_read'

### ISSUE THREAD

**Issue by AsioPanw** [PaloAltoNetworks/prismacloud-api-python#98]
## Describe the bug

**pcs_hosts_vulnerabilities_read.py** is returning the following error:

```
Testing Compute API Access ... done.

Getting Hosts (please wait) ...Traceback (most recent call last):
  File "pcs_hosts_vulnerabilities_read.py", line 35, in <module>
    hosts = pc_api.hosts_list_read()
AttributeError: 'PrismaCloudAPI' object has no attribute 'hosts_list_read'. Did you mean: 'audits_list_read'?
```

## Expected behavior

Being able to list hosts vulnerabilities from Compute

## Current behavior

Looks like the API handler misses the related function

**Comment by tkishel** [comment]
Are you using the current version of the package?

The `hosts_list_read()` method is defined there:

https://github.com/PaloAltoNetworks/prismacloud-api-python/blob/4.2.3/prismacloud/api/compute/_hosts.py#L9

**Comment by AsioPanw** [comment]
Nevermind... I was using 4.0 package with the script.. Thanks Thomas and sorry for inconvenience!

**Comment by tkishel** [comment]
Not an inconvenience at all!
